window.bdUniverseConfig = {
  // Edit these values to replace the photos and text shown in the app.
  // You can also use local file paths like "images/photo1.jpg" if needed.
  memories: [
    {
      id: "m1",
      title: "First Spark whaat",
      description: "The moment everything felt new — like the universe quietly saying hello.",
      textureUrl: "https://imgur.com/zZ5SVzA",
      radius: 7.5,
      speed: 0.22,
      size: 0.9,
      ring: true,
    },
    {
      id: "m2",
      title: "Laugh Orbit",
      description: "A day of effortless laughter that keeps circling back in my mind.",
      textureUrl: "https://picsum.photos/1024/768?random=2",
      radius: 10.5,
      speed: 0.17,
      size: 1.05,
      ring: false,
    },
    {
      id: "m3",
      title: "Golden Hour",
      description: "Soft light, warm air, and the feeling that time slowed down for us.",
      textureUrl: "https://picsum.photos/1024/768?random=3",
      radius: 13.6,
      speed: 0.13,
      size: 1.2,
      ring: true,
    },
    {
      id: "m4",
      title: "Starlit Talk",
      description: "When we spoke about everything and nothing, and it still meant the world.",
      textureUrl: "https://picsum.photos/1024/768?random=4",
      radius: 16.9,
      speed: 0.1,
      size: 1.35,
      ring: false,
    },
    {
      id: "m5",
      title: "Little Adventures",
      description: "The small detours that somehow became the biggest memories.",
      textureUrl: "https://picsum.photos/1024/768?random=5",
      radius: 20.8,
      speed: 0.08,
      size: 1.55,
      ring: true,
    },
    {
      id: "m6",
      title: "Home Gravity",
      description: "No matter how far the day travels, it always comes back to you.",
      textureUrl: "https://picsum.photos/1024/768?random=6",
      radius: 25.3,
      speed: 0.06,
      size: 1.85,
      ring: false,
    },
  ],
  final: {
    title: "🎉 HAPPY BIRTHDAY 🎉",
    subtitleDefault: "A sky made just for you",
    subtitleCelebrate: "🌟 You Are My Universe 🌟",
    backButton: "Back to the universe",
    hint: "or press Esc",
  },
};
